### ISSUE TITLE
「Gtk應用程式」的「Icon Theme」沒有跟隨「暗色系」的設定

### ISSUE THREAD

**Issue by samwhelp** [LingmoOS/lingmo-settings#27]
## 測試環境

* [Lingmo OS 2.0 Hydrogen](https://github.com/orgs/LingmoOS/discussions/20)
* lingmo-settings 2.1.5-rc1

## 測試範例

以「Mousepad」這個「Gtk應用程式」為例。

執行下面指令，安裝「mousepad」。

``` sh
sudo apt-get install mousepad
```

## 亮色系

透過「`lingmo-settings -m appearance`」，當設定是「亮色系」的時候，顯示如下圖

![亮色系](https://github.com/user-attachments/assets/370e6fd3-0d06-4d93-9b77-807cb5f6bc7d)

關於「~/.config/gtk-3.0/settings.ini」的內容如下

``` ini
[Settings]
gtk-application-prefer-dark-theme=false
gtk-enable-animations=true
gtk-font-name=Noto Sans 9
gtk-icon-theme-name=Crule
gtk-theme-name=Lingmo-light
```

## 暗色系/ 非預期

透過「`lingmo-settings -m appearance`」，當設定是「暗色系」的時候，顯示如下圖

![暗色系/ 非預期](https://github.com/user-attachments/assets/54426e16-0c6f-49ea-b90a-2e9690058dc7)

關於「~/.config/gtk-3.0/settings.ini」的內容如下

``` ini
[Settings]
gtk-application-prefer-dark-theme=true
gtk-enable-animations=true
gtk-font-name=Noto Sans 9
gtk-icon-theme-name=Crule
gtk-theme-name=Lingmo-dark
```

> 非預期的是「`gtk-icon-theme-name=Crule`」這一行。

## icons

執行

``` sh
ls /usr/share/icons/ -1
```

顯示

```
Adwaita
breeze
breeze-dark
Crule
Crule-dark
default
desktop-base
gnome
hicolor
HighContrast
lingmo-dark
lingmo-light
locolor
Tango
vendor
```

## 暗色系 / 預期

手動編輯「~/.config/gtk-3.0/settings.ini」的內容如下

``` ini
[Settings]
gtk-application-prefer-dark-theme=true
gtk-enable-animations=true
gtk-font-name=Noto Sans 9
gtk-icon-theme-name=Crule-dark
gtk-theme-name=Lingmo-dark
```

也就是設定「`gtk-icon-theme-name=Crule-dark`」，

> Mousepad 就會如下圖我們預期的顯示，可以看到工具列那裡的圖示就會是套用「暗色系」的「Icon Theme」。

![暗色系 / 預期](https://github.com/user-attachments/assets/d5224d42-aad4-481e-92cc-4c68291db442)

**Comment by samwhelp** [comment]
剛剛我收到通知，看到專案程式碼有修正了，非常感謝。

不過我看了一下修改後的程式碼，額外產生了一個疑問，


> 修正前的程式碼片段

``` cpp
    settings.setValue("gtk-icon-theme-name", m_iconTheme);
```

> 修正後的[程式碼片段](https://github.com/LingmoOS/lingmo-core/blob/main/settings-daemon/theme/thememanager.cpp#L459)如下

``` cpp
    settings.setValue("gtk-icon-theme-name", isDarkMode() ? "Crule-dark" : "Crule");
```

> 我的疑問是，上面的程式碼，雖然可以滿足修正我原本提到的議題

> 不過我猜好像會讓另一個功能會部份失效了。

> 也就是讓「設定Icon Theme」的功能不如預期，參考下面的說明。

參考下面的「[程式碼片段](https://github.com/LingmoOS/lingmo-core/blob/main/settings-daemon/theme/thememanager.cpp#L605-L619)」

``` cpp
QString ThemeManager::iconTheme() const
{
    return m_iconTheme;
}

void ThemeManager::setIconTheme(const QString &iconTheme)
{
    if (m_iconTheme == iconTheme)
        return;

    m_iconTheme = iconTheme;
    m_settings->setValue("IconTheme", m_iconTheme);
    updateGtk3Config();
    emit iconThemeChanged();
}
```

對照我在另一篇[討論串](https://github.com/orgs/LingmoOS/discussions/20#discussioncomment-10852058)提到的概念，


> 原本在「Lingmo」環境，也可以透過「dbus」來設定「Icon Theme」，

以下是參考指令

## dbus-icon-theme-set

執行下面指令，將「`Icon Theme`」設定為「`Crule-dark`」。

``` sh
qdbus com.lingmo.Settings /Theme com.lingmo.Theme.setIconTheme "Crule-dark"
```

## dbus-icon-theme-get

執行下面指令，獲得目前設定的「`Icon Theme`」。

``` sh
qdbus com.lingmo.Settings /Theme com.lingmo.Theme.iconTheme
```

顯示

```
Crule-dark
```


## ~/.config/gtk-3.0/settings.ini

> 在「dbus-icon-theme-set」後，在「`~/.config/gtk-3.0/settings.ini`」也會被設定。

執行

``` sh
grep '^gtk-icon-theme-name=' ~/.config/gtk-3.0/settings.ini
```

顯示

```
gtk-icon-theme-name=Crule-dark
```




以上補充說明，報告完畢

**Comment by elysia-best** [comment]
ok 收到

**Comment by elysia-best** [comment]
在 https://github.com/LingmoOS/lingmo-core/pull/17 修复了。提供了一个新的接口来设置dark模式下的theme
