### ISSUE TITLE
Background setting page wrong

### ISSUE THREAD

**Issue by aksharlabs** [LingmoOS/lingmo-settings#3]
The page for set backgrounds is displaying wlan pahe
![20240221_123848](https://github.com/LingmoOS/lingmo-settings/assets/74598801/12aed3d9-2408-41df-8680-96a3b272a5a0)

**Comment by elysia-best** [comment]
Added to bug tracker.

**Comment by elysia-best** [comment]
This is fix by https://github.com/LingmoOS/lingmo-settings/commit/0028a698313da88e2ba87412796a904e90ad2eb4

**Comment by elysia-best** [comment]
Close it @lingmo-dream

**Comment by lingmo-dream** [comment]
已关闭
