### ISSUE TITLE
重构系统更新

### ISSUE THREAD

**Issue by lingmo-dream** [LingmoOS/lingmo-settings#5]
@ganyuanzhen 
你的能力很不错，所以。。。
新任务来了（嘿嘿）：请在设置中加入更新页面，检查更新不是使用qapt，而且从服务器现在JSON文件，将其中的版本号与本地作对比，以此来判断是否需要更新。
（注，当点击“现在安装更新包”时，解压刚才下载的tar.xz文件，使用apt安装tar中的deb包（

**Comment by lingmo-dream** [comment]
类似于deepin的系统更新

**Comment by lingmo-dream** [comment]
可显示changelog

**Comment by elysia-best** [comment]
嘿嘿，其实我的Qt也才学了不久啦～

**Comment by lingmo-dream** [comment]
对了，在完成其他问题之前，先完成此功能（后面的更新和修复希望通过这个来完成更新，还有一个原因是目前的系统更新是使用qapt，所以会有很多问题，最大的问题就是更新后grub文件损坏，这应该是apt的特性）所以这个功能应该先完成，以减少更新失败的风险。

**Comment by elysia-best** [comment]
ok

**Comment by elysia-best** [comment]
![图片](https://github.com/LingmoOS/lingmo-settings/assets/39023210/9e1501a8-b809-4575-bd19-7ee695e77ea3)
这个UI如何～～嘿嘿
（要开学力 呜呜呜

**Comment by lingmo-dream** [comment]
Good job

**Comment by lingmo-dream** [comment]
不错👍

**Comment by lingmo-dream** [comment]
后面再看看更新日志的显示效果吧

**Comment by lingmo-dream** [comment]
你的技术很不错，未来可期👍

**Comment by lingmo-dream** [comment]
检查更新的等待用BusyIndicator来向用户反馈
LingmoUI.BusyIndicator{}

**Comment by lingmo-dream** [comment]
功能预计何时做好

**Comment by elysia-best** [comment]
正在实现一个基本的请求更新的业务逻辑。争取在开学前弄好吧（眼睛都要费了哈哈哈

计划服务器返回一个这样的json 

```json

示例
{
  "code": 200,
  "message": "success",
  "data": [
    {
      "package-name": "liblingmo",
      "version": "9.9.9-10",
      "description": "Core package for LingmoOS",
      "changelog": "Added some functions",
      "update-date": "1970-09-09 06:25:00"
    }
  ]
}
```
然后直接使用QProcess + dpkg 查询本地对应软件包信息。

之后，借用spark-store的ssinstal修改版下载安装更新。 这样做，LingmoOS的更新源就不用加入系统源。

**Comment by elysia-best** [comment]
明天开学，赶完了嘿嘿～

**Comment by lingmo-dream** [comment]
Thank you bro

**Comment by elysia-best** [comment]
注：这个更新的下载支持多服务器多线程（用aria2实现），可以部署多个镜像服务器（目录结构必须一直）以提高下载速度

**Comment by lingmo-dream** [comment]
嗯嗯

**Comment by lingmo-dream** [comment]
有没有测试的截图，我看看效果，目前我不方便测试

**Comment by elysia-best** [comment]
# 检查到更新
其实一直会有，还没有做比较本地版本的功能
![图片](https://github.com/LingmoOS/lingmo-settings/assets/39023210/fb80e59d-0957-4639-bd04-61fd3c8cb78f)
# 下载错误
![图片](https://github.com/LingmoOS/lingmo-settings/assets/39023210/31781301-c94f-44ff-950f-acb8da78b85f)

# 授权安装界面
![图片](https://github.com/LingmoOS/lingmo-settings/assets/39023210/89bf6ba3-75dd-48ed-b0d2-6261b1133c06)

**Comment by elysia-best** [comment]
目前还没有做错误后重试成功的判断。所以即使重试ok了还是会显示error哈哈。不过对应的item状态会显示成功

**Comment by elysia-best** [comment]
下面的检查时间还没修改，不过不是关键功能。哈哈

**Comment by lingmo-dream** [comment]
嗯嗯，不错

**Comment by lingmo-dream** [comment]
可以考虑实现更新日志的功能

**Comment by lingmo-dream** [comment]
当然，也可以我来做

**Comment by elysia-best** [comment]
更新日志是有的，但是必须在服务器API返回的json中给出。点击检查更新结果项就会展开该项的信息。

**Comment by lingmo-dream** [comment]
感谢代码贡献，我后面在网站中做一个贡献名单

**Comment by lingmo-dream** [comment]
> 更新日志是有的，但是必须在服务器 API 返回的 json 中给出。点击检查更新结果项即可展开订单的信息。

不错

**Comment by elysia-best** [comment]
# 下一步
- [x] 实现获取到服务器信息后，和本地的版本号比较
- [ ] 添加一个出错了显示的图标
- [ ] 修正出现错误重试后的逻辑，显示正确的文案
- [ ] 添加翻译
- [ ] 实现对下载的软件包的hash check（已经有了，但是没测试）
- [x] 修正免密码安装
- ...

**Comment by elysia-best** [comment]
#9

**Comment by elysia-best** [comment]
Archive this as it is continued by #12
